import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []

def md(text):
    cells.append(nbf.v4.new_markdown_cell(text))

def code(text):
    cells.append(nbf.v4.new_code_cell(text))

md("# Marketing Mix Attribution\n"
   "Which channels actually drive conversions, and how should budget be reallocated?\n\n"
   "Data: `data/touchpoints.csv` (lead-level, one row per touchpoint) and `data/spend.csv` "
   "(weekly spend per channel). Generated by `src/generate_data.py`.")

code("import pandas as pd\n"
     "import numpy as np\n"
     "import matplotlib.pyplot as plt\n"
     "import itertools\n\n"
     "touchpoints = pd.read_csv('../data/touchpoints.csv', parse_dates=['touchpoint_timestamp'])\n"
     "spend = pd.read_csv('../data/spend.csv', parse_dates=['period'])\n"
     "touchpoints.head()")

md("## 1. Data overview")
code("print(touchpoints.shape, spend.shape)\n"
     "print(touchpoints['lead_id'].nunique(), 'unique leads')\n"
     "leads = touchpoints.sort_values('touchpoint_order').drop_duplicates('lead_id', keep='last')\n"
     "print('Overall conversion rate:', leads['converted'].mean())")

md("## 2. Exploratory analysis\n"
   "- Conversion rate by first-touch channel vs last-touch channel (the disagreement is the hook)\n"
   "- Avg touchpoints per converted vs non-converted lead\n"
   "- Channel co-occurrence")

code("first_touch = touchpoints[touchpoints['touchpoint_order'] == 1].set_index('lead_id')['channel']\n"
     "last_touch = touchpoints.sort_values('touchpoint_order').groupby('lead_id').last()['channel']\n"
     "conv = touchpoints.drop_duplicates('lead_id').set_index('lead_id')['converted']\n\n"
     "cmp = pd.DataFrame({'first_touch': first_touch, 'last_touch': last_touch, 'converted': conv})\n"
     "first_rate = cmp.groupby('first_touch')['converted'].mean().rename('first_touch_conv_rate')\n"
     "last_rate = cmp.groupby('last_touch')['converted'].mean().rename('last_touch_conv_rate')\n"
     "pd.concat([first_rate, last_rate], axis=1).sort_values('last_touch_conv_rate', ascending=False)")

code("touch_counts = touchpoints.groupby('lead_id').size().rename('n_touches')\n"
     "pd.concat([touch_counts, conv], axis=1).groupby('converted')['n_touches'].mean()")

code("paths = touchpoints.groupby('lead_id')['channel'].apply(lambda s: sorted(set(s)))\n"
     "channels = sorted(touchpoints['channel'].unique())\n"
     "co = pd.DataFrame(0, index=channels, columns=channels)\n"
     "for path in paths:\n"
     "    for a, b in itertools.combinations(path, 2):\n"
     "        co.loc[a, b] += 1\n"
     "        co.loc[b, a] += 1\n"
     "co")

md("## 3. Attribution modeling\n"
   "Build in this order: last-touch → first-touch → linear/position-based → "
   "regression-based → Shapley-value.")

md("### 3.1 Last-touch attribution (naive baseline)")
code("last_touch_credit = cmp[cmp['converted'] == 1].groupby('last_touch').size()\n"
     "last_touch_credit")

md("### 3.2 First-touch attribution (naive baseline #2)")
code("first_touch_credit = cmp[cmp['converted'] == 1].groupby('first_touch').size()\n"
     "first_touch_credit")

md("### 3.3 Linear / position-based attribution")
code("def linear_attribution(touchpoints_df):\n"
     "    conv_leads = touchpoints_df[touchpoints_df['converted'] == 1]\n"
     "    credit = {}\n"
     "    for lead_id, grp in conv_leads.groupby('lead_id'):\n"
     "        chs = grp['channel'].tolist()\n"
     "        w = 1 / len(chs)\n"
     "        for ch in chs:\n"
     "            credit[ch] = credit.get(ch, 0) + w\n"
     "    return pd.Series(credit).sort_values(ascending=False)\n\n"
     "linear_credit = linear_attribution(touchpoints)\n"
     "linear_credit")

md("### 3.4 Regression-based attribution")
code("from sklearn.linear_model import LogisticRegression\n\n"
     "presence = pd.crosstab(touchpoints['lead_id'], touchpoints['channel'])\n"
     "presence = (presence > 0).astype(int)\n"
     "y = touchpoints.drop_duplicates('lead_id').set_index('lead_id')['converted'].loc[presence.index]\n\n"
     "clf = LogisticRegression(max_iter=1000)\n"
     "clf.fit(presence, y)\n"
     "reg_credit = pd.Series(clf.coef_[0], index=presence.columns).sort_values(ascending=False)\n"
     "reg_credit")

md("### 3.5 Shapley-value attribution (differentiator)\n"
   "**Important fix vs. a naive implementation:** computing exact Shapley values over the "
   "*full* 7-channel universe requires a value for the grand coalition (all 7 channels on one "
   "lead's path). But leads here only ever have 1–5 touches, so that coalition never occurs in "
   "the data — a universal-powerset implementation silently falls back to 0 for it, which "
   "breaks the Shapley efficiency property and produces unstable, misleading credit (this is a "
   "classic multi-touch-attribution pitfall, not just noise).\n\n"
   "**The fix:** compute Shapley values *per lead*, over only the channels that lead actually "
   "touched (so the \"grand coalition\" is just that lead's own path — always observed in the "
   "data, never a hypothetical). Credit is then summed across leads, which also puts Shapley on "
   "the same scale (attributed conversions) as the other four methods above — directly "
   "comparable, no unit conversion needed.")
code("from itertools import permutations\n\n"
     "channel_list = sorted(touchpoints['channel'].unique())\n"
     "presence_conv = presence.join(y.rename('converted'))\n"
     "_cache = {}\n\n"
     "def subset_rate(subset):\n"
     "    key = frozenset(subset)\n"
     "    if key in _cache:\n"
     "        return _cache[key]\n"
     "    if not subset:\n"
     "        rate = 0.0\n"
     "    else:\n"
     "        mask = (presence_conv[list(subset)].sum(axis=1) == len(subset))\n"
     "        rate = presence_conv.loc[mask, 'converted'].mean() if mask.sum() > 0 else np.nan\n"
     "    _cache[key] = rate\n"
     "    return rate\n\n"
     "def shapley_per_lead(touchpoints_df):\n"
     "    credit = {ch: 0.0 for ch in channel_list}\n"
     "    lead_paths = touchpoints_df.groupby('lead_id')['channel'].apply(lambda s: tuple(sorted(set(s))))\n"
     "    path_counts = lead_paths.value_counts()  # leads sharing the exact same channel SET, computed once each\n"
     "    for path, n_leads in path_counts.items():\n"
     "        chs = list(path)\n"
     "        perms = list(permutations(chs))\n"
     "        shap_local = {ch: 0.0 for ch in chs}\n"
     "        for perm in perms:\n"
     "            seen = []\n"
     "            prev_val = 0.0\n"
     "            for ch in perm:\n"
     "                seen.append(ch)\n"
     "                val = subset_rate(tuple(sorted(seen)))\n"
     "                if np.isnan(val):\n"
     "                    val = prev_val  # unseen combo in data: assume no marginal change\n"
     "                shap_local[ch] += (val - prev_val)\n"
     "                prev_val = val\n"
     "        for ch in chs:\n"
     "            shap_local[ch] /= len(perms)\n"
     "            credit[ch] += shap_local[ch] * n_leads\n"
     "    return pd.Series(credit).sort_values(ascending=False)\n\n"
     "shapley_credit = shapley_per_lead(touchpoints)\n"
     "shapley_credit")

md("## 4. Compare & recommend")
code("comparison = pd.DataFrame({\n"
     "    'last_touch': last_touch_credit,\n"
     "    'first_touch': first_touch_credit,\n"
     "    'linear': linear_credit,\n"
     "    'regression_coef': reg_credit,\n"
     "    'shapley': shapley_credit,\n"
     "}).fillna(0)\n"
     "comparison['shapley_share'] = comparison['shapley'] / comparison['shapley'].sum()\n"
     "comparison.sort_values('shapley', ascending=False)")

code("total_spend = spend.groupby('channel')['spend'].sum()\n"
     "comparison['total_spend'] = total_spend\n"
     "comparison['cac_shapley'] = comparison['total_spend'] / comparison['shapley'].replace(0, np.nan)\n"
     "comparison['cac_last_touch'] = comparison['total_spend'] / comparison['last_touch'].replace(0, np.nan)\n"
     "comparison[['total_spend', 'shapley', 'cac_shapley', 'last_touch', 'cac_last_touch']].sort_values('cac_shapley')")

md("**Business recommendation:** write it here once you've looked at the table above — which "
   "channel does last-touch over-credit relative to Shapley (compare the `last_touch` vs "
   "`shapley` columns and the two CAC columns), which channel is under-credited despite being "
   "a real driver, and the $ or lead-volume shift you'd propose.")

md("## 5. Deliverables checklist\n"
   "- [ ] This notebook (EDA → attribution → comparison)\n"
   "- [ ] `reports/README.md` — problem, method comparison, recommendation\n"
   "- [ ] Optional: Streamlit page — channel attribution bar chart + ROI/CAC table")

nb['cells'] = cells
with open('/home/claude/marketing-mix-attribution/notebooks/marketing_mix_attribution.ipynb', 'w') as f:
    nbf.write(nb, f)
print("Notebook written.")
